---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2016
    os_type: windows
    transport:
      name: winrm
      elevated: true

suites:
  - name: default
    run_list:
      - recipe[cb_cis_windows_2016::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
